const data = {
    products: [
        {
            _id: '111111111111111111111111',
            name: 'Cam Dai Loan',
            category: 'Fruit',
            image: './assets/images/products/cam.png',
            price: 4,
            brand: 'Minh Long',
            rating: 4.3,
            numReviews: 20,
            countInStock: 10,
        },
        {
            _id: '222222222222222222222222',
            name: 'Chanh Phu Quy',
            category: 'Fruit',
            image: './assets/images/products/chanh.png',
            price: 3,
            brand: 'Minh Long',
            rating: 4.5,
            numReviews: 10,
            countInStock: 4,
        },
        {
            _id: '333333333333333333333333',
            name: 'Dau Da Lat',
            category: 'Fruit',
            image: './assets/images/products/dau.png',
            price: 7,
            brand: 'Minh Long',
            rating: 4.3,
            numReviews: 18,
            countInStock: 10,
        },
        {
            _id: '444444444444444444444444',
            name: 'Tao Trung Quoc',
            category: 'Fruit',
            image: './assets/images/products/tao.png',
            price: 4,
            brand: 'Minh Long',
            rating: 4.6,
            numReviews: 21,
            countInStock: 10,
        },
        {
            _id: '555555555555555555555555',
            name: 'Thom Yen Bai',
            category: 'Fruit',
            image: './assets/images/products/thom.png',
            price: 4,
            brand: 'Minh Long',
            rating: 4.4,
            numReviews: 20,
            countInStock: 10,
        },
        {
            _id: '666666666666666666666666',
            name: 'Xoai Quang Ninh',
            category: 'Fruit',
            image: './assets/images/products/xoai.png',
            price: 4,
            brand: 'Minh Long',
            rating: 3.6,
            numReviews: 20,
            countInStock: 10,
        },
    ],
};

export default data;
